apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jitsi
  labels:
    k8s-app: prosody
  name: prosody
spec:
  selector:
    matchLabels:
      shard: "1"
  template:
    spec:
      # avoid that pods of different shards share zone
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: shard
                operator: In
                values:
                - "0"
            topologyKey: "topology.kubernetes.io/zone"
    metadata:
      labels:
        shard: "1"
