apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jitsi
  labels:
    k8s-app: jicofo
  name: jicofo
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: shard
                operator: In
                values: 
                - "1"
            topologyKey: "topology.kubernetes.io/zone"
      containers:
        - name: jicofo
          env:
            - name: XMPP_SERVER
              value: shard-0-prosody
