apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: jitsi
  name: jvb
spec:
  selector:
    matchLabels:
      k8s-app: jvb
      shard: "0"
  template:
    metadata:
      labels:
        k8s-app: jvb
        shard: "0"
    spec:
      # Avoid that Pods of different shards share zone:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: shard
                operator: In
                values: 
                - "1"
            topologyKey: "topology.kubernetes.io/zone"
      containers:
        - name: jvb
          env:
            - name: XMPP_SERVER
              value: shard-0-prosody
          args:
            - "30300"
            - "/init"
