apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jitsi
  labels:
    k8s-app: prosody
  name: prosody
spec:
  selector:
    matchLabels:
      shard: "0"
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: shard
                operator: In
                values: 
                - "1"
            topologyKey: "topology.kubernetes.io/zone"
    metadata:
      labels:
        shard: "0"
