apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jitsi
  labels:
    k8s-app: web
  name: web
spec:
  # Avoid that Pods of different shards share zone:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: shard
                operator: In
                values: 
                - "1"
            topologyKey: "topology.kubernetes.io/zone"
      containers:
        - name: web
          env:
            - name: XMPP_SERVER
              value: shard-0-prosody
            - name: XMPP_BOSH_URL_BASE
              value: http://shard-0-prosody:5280
