bases:
  - ../../../base/ops

resources:
  - bbb-endpoints.yaml
  - certificate.yaml
  - elasticsearch.yaml

patchesStrategicMerge:
  - grafana-deployment-patch.yaml
  - grafana-ingress-patch.yaml
  - prometheus-prometheus-patch.yaml
