apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prosody-pod-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      k8s-app: prosody
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - port: metrics