apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: fluentd
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch-es-http.logging.svc.cluster.local"
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "https"
            - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
              value: "false" # not necessary within cluster
            - name: FLUENT_ELASTICSEARCH_USER
              value: "elastic"
            # delete fluentd password and get new one from secret
            - $patch: delete
              name: FLUENT_ELASTICSEARCH_PASSWORD
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-es-elastic-user
                  key: elastic
