apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- logging-namespace.yaml
- eck-crd.yaml
- kibana.yaml
- fluentd-daemonset-elasticsearch-rbac.yaml

patchesStrategicMerge:
- fluentd-daemonset-patch.yaml
