# File realm in ES format (from the CLI or manually assembled)
kind: Secret
apiVersion: v1
metadata:
  name: my-filerealm-secret
  namespace: logging
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kube-system"
data:
  users: |-
    Zmx1ZW50ZDo3akRBTVFzZDMyYXM5MElEYWRQZg==
  users_roles: |-
    c3VwZXJ1c2VyOmZsdWVudGQ=