apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jitsi-haproxy-ingress
  namespace: jitsi
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/config-backend: |
      stick-table type string len 128 size 2k expire 1d
      stick on path if !{ path_beg /images || path_beg /lang || path_beg /libs || path_beg /http-bind || path_beg /css }   
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 80
