apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: jitsi
  name: jvb-hpa
spec:
  minReplicas: 2
  maxReplicas: 6
  metrics:
      pods:
        target:
          averageValue: 100000

