apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- jvb-entrypoint-configmap.yaml
- jvb-shutdown-configmap.yaml
- jvb-pod-monitor.yaml
- service-per-pod-decoratorcontroller.yaml
- jvb-statefulset.yaml
