apiVersion: v1
kind: Service
metadata:
  name: haproxy-0
  namespace: loadbalancer
spec:
  selector:
    statefulset.kubernetes.io/pod-name: haproxy-0
  ports:
    - name: "peering"
      port: 1024
  type: ClusterIP
